#!/usr/bin/env bash
# Script install Nginx web server to server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello world" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
