#!/usr/bin/env bash
# Script configures nginx server to redirect to another page

ADD301_REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"
ADD301_404="error_page 404 /custom_404.html;\n\\t location = /custom_404.html {\n\t\t root /usr/share/nginx/html;\n\tinternal;\n\t}\n"
PATTERN="#error_page 404 /404.html;"

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello world" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "s@$PATTERN@"ADD301_404@" /etc/nginx/sites-available/default
sudo service nginx start
